[package]
name = "certblip/luau-di"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"

realm = "shared"

exclude = [
    ".github",
    "docs",
    "demo",
    "test",
    "*.rbxl",
    "*.rbxlx"
]

[dependencies]
